### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by aiporre** [imagen2/imagen_databank#1]
Hello Imagen Team, I would like to use you dataset in PhD project, so I wanted to apply to get access to the data. Is this possible? I see that the website is down. https://imagen-project.org/

**Comment by DimitriPapadopoulos** [comment]
The historical head of the project overviews data access for the consortium:
https://psychiatrie-psychotherapie.charite.de/en/research/population_neuroscience/

We cannot really help as the database team. I know the Imagen web site is down, hopefully it will be up again in a few weeks or months.
